spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console